Repository toodofun/gvm, pull requests merged in 2025-06, with the labels that each got.

#10 Support node install feature
  README.md
  README_zh.md
  internal/utils/compress/compress.go
  internal/utils/path/path.go
  languages/golang/golang.go
  languages/helpers.go
  languages/language.go
  languages/node/node.go
  languages/node/node_test.go
  languages/type.go
  languages/type_test.go
Labels: enhancement, dependencies, kind/bug

#15 Fixed the issue of node language installation package on Windows and setting the default language version as ineffective #11
  internal/util/env/path_manager.go
  languages/language.go
  languages/node/node.go
Labels: kind/bug

#17 Feature/ruima
  Makefile
  README.md
  README_zh.md
  internal/http/client_test.go
  internal/util/env/env_manager.go
  internal/util/env/env_manager_test.go
  internal/util/env/env_manager_unix.go
  internal/util/env/env_manager_windows.go
  internal/util/env/path_manager.go
  internal/util/version/version_test.go
  internal/view/application_test.go
  internal/view/key_action_test.go
  internal/view/view_table_search_test.go
  languages/golang/golang.go
  languages/golang/golang_test.go
  languages/language.go
  languages/node/node.go
Labels: kind/bug

#18 Update name for image registry
  .github/workflows/release.yml
  languages/golang/golang.go
  languages/type_test.go
Labels: area/testing, kind/bug

#19 Fix: rename module name
  cmd/current.go
  cmd/install.go
  cmd/ls.go
  cmd/ls_remote.go
  cmd/root.go
  cmd/root_test.go
  cmd/ui.go
  cmd/uninstall.go
  cmd/use.go
  cmd/use_test.go
  cmd/version.go
  go.mod
  internal/http/client.go
  internal/log/log.go
  internal/log/log_test.go
  internal/util/color/color_test.go
  internal/util/compress/compress.go
  internal/util/path/path.go
  internal/util/path/path_test.go
  internal/view/application.go
  internal/view/header.go
  internal/view/key_action_test.go
  internal/view/model_language_versions.go
  internal/view/model_languages.go
  internal/view/page_language_versions.go
  internal/view/page_languages.go
  internal/view/view_installer.go
  internal/view/view_table_search.go
  languages/golang/golang.go
  languages/helpers.go
  languages/language.go
  languages/node/node.go
  languages/node/node_test.go
  main.go
Labels: kind/bug, approved

#20 CI: triggered when the build phase condition is changed to push
  .github/workflows/gvm.yml
  .github/workflows/release.yml
Labels: kind/cleanup

#23 [closes #22] Fix: page display abnormality
  CHANGELOG/1.0.0.md
  internal/view/model_language_versions.go
  internal/view/page_language_versions.go
Labels: kind/bug

#24 docs: add release download icon in readme
  README.md
  README_zh.md
Labels: area/documentation

#26 docs: add usage pic
  README.md
  README_zh.md
  assets/gvm.gif
Labels: area/documentation

#27 docs: add how to use video
  README.md
  README_zh.md
  assets/language-versions.png
  assets/languages.png
Labels: area/documentation, kind/cleanup
